[package]
name = "punylisp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing_gc = {git = "https://github.com/Grissess/tracing_gc", branch = "main"}
